server:
  port: 4040
  
spring:
  datasource:
   driver-class-name: com.mysql.cj.jdbc.Driver
   url: jdbc:mysql://localhost:3306/raji
   username: root
   password: root
  jpa:
   show-sql: true
   database-platform: org.hibernate.dialect.MySQLDialect
   hibernate:
     ddl-auto: update
  batch:
   job: 
    enabled: false
   jdbc:
    initialize-schema: always
    
          
  
  
